@prefix = http://localhost:5000

### Obtain the service status and description

GET {{prefix}}/status

### Start the ibeacon scanner

POST {{prefix}}/ibeacon_scanner/start
Content-Type: application/json

{
    
}

### Stop the ibeacon scanner

POST {{prefix}}/ibeacon_scanner/stop
Content-Type: application/json

{

}


### Get ibeacon scanner settings

GET {{prefix}}/ibeacon_scanner/settings

### Set ibeacon scanner settings

PUT {{prefix}}/ibeacon_scanner/settings
Content-Type: application/json

{
    "uuid_filter": "ffffffff-bbbb-cccc-dddd-eeeeeeeeeeee",
    "scan_tick": 3,
    "run_flag": false,
    "fake_scan": true
}

### Get ibeacon scanner read beacons data

GET {{prefix}}/ibeacon_scanner/beacons_data
